[project]
name = 'bitthetix-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.bitthetix]
path = 'contracts/bitthetix.clar'
clarity_version = 2
epoch = 2.4

[contracts.mock-price-feed]
path = 'contracts/mock-price-feed.clar'
clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[contracts.sbtc]
path = 'contracts/sBTC/asset.clar'
clarity_version = 2
epoch = 2.4

[contracts.clarity-bitcoin-mini-deploy]
path = 'contracts/sBTC/clarity-bitcoin-mini-deploy.clar'
clarity_version = 2
epoch = 2.4

[contracts.clarity-bitcoin-mini]
path = 'contracts/sBTC/clarity-bitcoin-mini.clar'
clarity_version = 2
epoch = 2.4

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
